#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "Please provide a test name"
  exit 1
fi
file="testing/tests/$1.lua"

if [ ! -e "$file" ]; then
  echo "Test \"$1\" does not exist"
  exit 1
fi

cat $file | lua5.3
