#!/bin/bash
make moonshot
[ "$?" == 1 ] && exit 1

tests=( $(ls testing/tests | grep -e "\.lua$") )
for test in "${tests[@]}"; do
  echo "Test: $test"
  cat "testing/tests/$test" | ./moonshot --stdin --print | lua5.3 > bin/custom.txt
  cat "testing/tests/$test" | lua5.3 > bin/vanilla.txt
  diff bin/custom.txt bin/vanilla.txt
  echo ""
done
